import Head from 'next/head';
import Link from 'next/link';
const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>{'CowBoy Bebop'}</header>

      <main>
        <div>
          <Link href={'/products'}>products</Link>
          content
        </div>
      </main>

      <footer>{'@copyright CowBoy Bebop'}</footer>
    </div>
  );
};

export default Home;
